#810 nexus credentials
OWASP/wrongsecrets pull request #1046
Opened 2023-10-18 15:13 UTC by divyanshuagarwal-23

### What kind of changes does this PR include?
-Fixes

#### Description
As per #810 task one was to Create a settings.xml to connect to an imaginary Nexus repo, 
I have created the settings.xml file for the same
and have created a challenge reading the credential

### Relations
closes #810 

### References
issue: https://github.com/OWASP/wrongsecrets/issues/810
took ref from: https://github.com/sonatype/nexus-book-examples/blob/master/maven/settings/settings.xml

2023-10-18 15:14 UTC, divyanshuagarwal-23 commented
@commjoen please review this new PR, 
I will close the old one, which was causing issue due to challenge number

2023-10-18 19:38 UTC, commjoen requested changes
I was not able to get it running on my system in this shape. Can you please have a look at the comments for an alternative approach?

2023-10-18 19:38 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge42.java
> +      ScoreCard scoreCard, @Value("classpath:maven/settings/settings.xml") Resource resource) {
This resource does not exist (see below),  can you instead have a look at the code of Challenge12.java? here you can see how a file is loaded either from test resources or from a filepath within a docker container or from the resources.

2023-10-18 19:38 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge42.java
> +      return xmlConfiguration.getString("nexus.password");
this gives quite a few different exceptions. Can we do it with the jdk based parser?
```java
DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
        dbFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
        Document doc = dBuilder.parse(Paths.get(filepath "settings.xml").toFile());
        doc.getDocumentElement().normalize();
        return doc.getDocumentElement().getElementsByTagName("servers").item(0).getChildNodes().item(0).getNextSibling().getChildNodes().item(4).getNextSibling().getTextContent();
```
or something among these lines. And can you remove the entry from the pom.xml ?

2023-10-18 19:38 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge42.java
> +      log.warn("there was an exception with decrypting content in challenge42", e);
```suggestion
      log.warn("there was an exception with retrieving and parsing the xml content for  challenge42", e);
```

2023-10-18 19:38 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge42.java
> +      return "error_decryption";
```suggestion
      return "error_parsing";
```

2023-10-18 19:38 UTC, commjoen commented on src/test/java/org/owasp/wrongsecrets/challenges/docker/Challenge42Test.java
> +    Assertions.assertThat(challenge.answerCorrect(challenge.spoiler().solution())).isTrue();
```suggestion
    Assertions.assertThat(challenge.answerCorrect(challenge.spoiler().solution())).isTrue();
     Assertions.assertThat(challenge.answerCorrect("error_parsing").isFalse();
```

2023-10-20 20:58 UTC, commjoen commented on src/main/resources/explanations/challenge42.adoc
> +Storing nexus deployment credentials in your github project hardcoded is generally considered a bad practice because it undermines the security provided by encryption.
```suggestion
A developer wanted to configure his Nexus credentials and copy-pasted the configuration from the internal Confluence documentation site, while accidentally committing it to git!
Can you find the password?
```

2023-10-20 21:04 UTC, commjoen commented on src/main/resources/explanations/challenge42_reason.adoc
> +It is always recommended to store your credentials securely.
```suggestion
Storing the credentials of your artifact registry in your Github project is a bad practice, as others can use these credentials to login, pull, and sometimes push artifacts in the name of the identity user of which the credentials were committed to git.

We often see the situation getting worse by just having one user hardcoded in many configurations of their projects.
Alternatively, we often see the artifact registry credentials hardcoded in the internal documentation site of an organization. 
In all cases, we often end up with a compromised user used to inject payloads into the artifact registry.

This is why it is better to have service accounts and/or personal accounts and/or a federated approach for users to the artifact registry. Next, make sure that you never hardcode the credentials: instead: have them configured as part of a secrets management setup.

```

2024-01-01 21:36 UTC, bendehaan commented
Hello @divyanshuagarwal-23,

Thank you for your contribution. We appreciate your interest in helping improve WrongSecrets. However, we've noticed that there hasn't been any activity on this PR for several months.

We'll close this PR for now to maintain an efficient and organised workflow. Please don't be discouraged! We welcome you to reopen this PR or create a new one if you wish to continue your contribution in the future.

Feel free to reach out if you have any questions or need assistance.

Thank you for your understanding.

2024-01-01 21:36 UTC, closed without merging