refactor: simplify challenges when answer is fixed
OWASP/wrongsecrets pull request #1125
Opened 2023-12-10 20:16 UTC by nbaars

When the answer is always the same we can cache it and the challenge only need to implement one method. This removes the necessity to implement methods `spoiler()` and `answerCorrect()` in every subclass.

2023-12-12 05:13 UTC, commjoen commented
deploying the PR to https://arcane-scrubland-42646.herokuapp.com/

2023-12-12 06:33 UTC, commjoen requested changes
after doing some testing and reviewing: only a few small comments: can you have a look please?

2023-12-12 06:33 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/FixedAnswerChallenge.java
> +  private Supplier<String> cachedAnswer = Suppliers.memoize(() -> getAnswer());
CAn this be renamed to memorize?

2023-12-12 06:33 UTC, commjoen commented on CONTRIBUTING.md
> +
Can we add an example of a challenge with a random answer as well please?

2023-12-16 09:50 UTC, bendehaan approved these changes

2023-12-16 09:52 UTC, merged