Add misconfiguration for mounting in secret in during build
OWASP/wrongsecrets pull request #1790
Opened 2024-12-13 12:53 UTC by Shubham-Patel07

### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [x] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### To Do

-  [x] Embed the secret variable in https://github.com/OWASP/wrongsecrets/blob/master/.github/scripts/docker-create.sh and make sure it lands in a file in the docker container
-  [ ] create a challenge that reads the secret from that file and teaches why this is a bad idea (See contributing.md)

### Relations

Closes #812 

### Checklist:

-   [x] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] I added UI tests to ensure my UI changes work (when change in the overall UI, not needed if just adding a challenge)
-   [ ] The PR passes pre-commit hooks and automated tests

2024-12-13 12:56 UTC, Shubham-Patel07 commented
Hi @commjoen sir,
the env_var is not properly been injected to container for some reason 
Please check the Dockerfile 
https://github.com/Shubham-Patel07/wrongsecrets/blob/f0ed8fc7cd08eb43dc0aa78c434f39e5f1e97ec1/Dockerfile#L20-L26

2024-12-30 06:39 UTC, commjoen commented
Files have been shared over Slack ^^, looking forward to the challenge implementation good sir!

2025-01-03 21:43 UTC, commjoen commented on src/main/resources/explanations/challenge52.adoc
> +During their Docker Buildx process, a sensitive secret, meant to remain temporary and secure during the build phase, was accidentally embedded into the container's filesystem due to a misconfiguratio
@bendehaan and @Shubham-Patel07 : should we be more explicit that it is about the WrongSecrets container? Instead of acme.inc we might want to make it more explicit so people know what to look for?

2025-01-03 21:48 UTC, commjoen commented on src/main/resources/explanations/challenge52_hint.adoc
> +- *Acme Inc.* has misconfigured their Docker Buildx process, leading to sensitive secrets being embedded in the container's filesystem. Your task is to uncover these vulnerabilities.
Can we maybe show 2 different paths for solutions:
1. Show the secret from the docker-create script
2. Show how to get the secret by an exec into the container (using source code and env var to find the location)

2025-01-03 21:53 UTC, commjoen commented
Great progress @Shubham-Patel07 ! Can you please extend the set with the unit and integration tests please?

2025-02-02 19:05 UTC, Shubham-Patel07 commented on src/main/resources/explanations/challenge52_hint.adoc
> +- *Acme Inc.* has misconfigured their Docker Buildx process, leading to sensitive secrets being embedded in the container's filesystem. Your task is to uncover these vulnerabilities.
Yeah Now I've shown two paths in `challenge52_reason.adoc`

2025-02-02 19:07 UTC, Shubham-Patel07 commented on src/main/resources/explanations/challenge52.adoc
> +During their Docker Buildx process, a sensitive secret, meant to remain temporary and secure during the build phase, was accidentally embedded into the container's filesystem due to a misconfiguratio
Yeah i as well think I should keep it explicit to create containers

2025-02-03 08:24 UTC, commjoen requested changes
Just a final lap to go @Shubham-Patel07 ! Can you please have a look at the suggested changes, then we can merge this baby :)

2025-02-04 10:16 UTC, commjoen approved these changes

2025-02-04 10:43 UTC, merged