Beginner Guide Submission
OWASP/wrongsecrets pull request #653
Opened 2023-02-28 13:47 UTC by puneeth072003

### Submission of pictorial Beginner Guide including "How to add Challenges" part as requested and mentioned in the issue #558 and continuation to the PR #589 

What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [ ] A new challenge
-   [x] Additional documentation
-   [ ] Something else

Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [x] The PR passes pre-commit hooks and automated tests

2023-02-28 18:16 UTC, bendehaan requested changes
Great work @puneeth072003! A few minor nits and we're good to go. You can just commit these in a batch in the GitHub UI, you don't have to open a new PR.

2023-02-28 18:16 UTC, bendehaan commented on CONTRIBUTING.md
> +Basically, [*WrongSecrets*](https://owasp.org/www-project-wrongsecrets/) is an application which teaches how to not store secrets by offering challenges to the user, which helps the user to Self-refl
```suggestion
[*WrongSecrets*](https://owasp.org/www-project-wrongsecrets/) is an application teaching how to *not* store secrets by offering challenges to the user, helping the user to Self-reflect and correct those mistakes.
```

2023-02-28 18:16 UTC, bendehaan commented on CONTRIBUTING.md
> +    - ***Fill*** all the fields as shown below.
```suggestion
    - ***Fill out*** all the fields as shown below.
```

2023-02-28 18:16 UTC, bendehaan commented on CONTRIBUTING.md
> +  First make sure that you have an [Issue](https://github.com/OWASP/wrongsecrets/issues/new) reported for which a challenge is really wanted, And make sure the challenge is assigned to you, as others
```suggestion
  First make sure that you have an [Issue](https://github.com/OWASP/wrongsecrets/issues/new) reported for which a challenge is really wanted, And make sure the challenge is assigned to you, as others might be working on the challenge.
```

2023-02-28 18:16 UTC, bendehaan commented on CONTRIBUTING.md
> +  Please note that PRs for new challenges are only excepted when unit tests are added to prove that the challenge works. Normally tests should not immediately leak the actual secret, so leverage the
```suggestion
  Please note that PRs for new challenges are only accepted when unit tests are added to prove that the challenge works. Normally tests should not immediately leak the actual secret, so leverage the `.spoil()` functionality of your test implementation for this.
```

2023-02-28 18:16 UTC, bendehaan commented on CONTRIBUTING.md
> +    - Every thing must be in a separate **AsciiDoc files**.
```suggestion
    - Everything must be in separate **AsciiDoc files**.
```

2023-03-02 01:26 UTC, puneeth072003 commented
@bendehaan @commjoen If i run `pre-commit run -a` before adding a commit it modifies all the markdown files in the project,
including the Contributing.md shall i commit all the modifications it made?

2023-03-02 05:40 UTC, commjoen commented
> @bendehaan @commjoen If i run `pre-commit run -a` before adding a commit it modifies all the markdown files in the project,
> 
> including the Contributing.md shall i commit all the modifications it made?
> 
> In order to pass the pre-commit test....:-)

Yes

2023-03-02 14:23 UTC, puneeth072003 commented
@bendehaan How can i fix that test that has failed?

2023-03-02 14:33 UTC, bendehaan approved these changes
Looks good now - thanks for your contribution!

2023-03-02 14:36 UTC, commjoen approved these changes
That was a long journey! Awesome! Welcome to the team of contributors!

2023-03-02 14:44 UTC, merged