Adding Challenge 28
OWASP/wrongsecrets pull request #690
Opened 2023-03-10 17:04 UTC by puneeth072003

### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [x] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### Description
Adding a new challenge 28 as asked in issue #423 completing the Part 1 of that issue 
-   [x]  a secret in a closed github issue ^^.

### Relations
issue #42

### Checklist:

-   [x] All the contributions made are solely the work of me and my co-authors
-   [x] I tested the changes in this PR (if applicable)
-   [x] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [x] The PR passes pre-commit hooks and automated tests

2023-03-10 17:08 UTC, puneeth072003 commented
@commjoen @bendehaan 
I still have to create a issue with the secret.

2023-03-10 22:14 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge28.java
> +    private String SecretKey="asdfdpuYUIadbaoasdpa07kj2003";
```suggestion
    private String SecretKey=new String(Base64.decode(new String(Base64.decode("WVhOa1ptUndkVmxWU1dGa1ltRnZZWE5rY0dFd04ydHFNakF3TXc9PQ=="))));;
```

2023-03-10 22:22 UTC, commjoen requested changes
Hi @puneeth072003 ! Your first challenge! thank you!
Here are some feedback items based on the textual and linting results. You can, for each suggestion click on "commit suggestion" or "add suggestion to batch"in the files overview, and then quickly add the recommended changes.
After that, let's file the issue :D !
Love this!

2023-03-10 22:22 UTC, commjoen commented on src/main/resources/explanations/challenge28.adoc
> +User reveals his `AWS Secret key` by mistake while describing conversation between him and his friend while discussing about his plans for upcoming days in a `GitHub issue` then realizes it and close
```suggestion
A user reveals his `AWS Secret key` by mistake while describing conversation between him and his friend while discussing about his plans for upcoming days in a `GitHub issue` then realizes it and closes that issue.
```

2023-03-10 22:22 UTC, commjoen commented on src/test/java/org/owasp/wrongsecrets/challenges/docker/Challenge28Test.java
> +    private String SecretKey="asdfdpuYUIadbaoasdpa07kj2003";
```suggestion
    private String secretKey=new String(Hex.decode("61736466647075595549616462616f617364706130376b6a32303033"));
```

2023-03-10 22:22 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge28.java
> +        this.SecretKey = SecretKey;
```suggestion
```

2023-03-10 22:22 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge28.java
> +        return new Spoiler(SecretKey);
```suggestion
        return new Spoiler(secretKey);
```

2023-03-10 22:22 UTC, commjoen commented on src/main/java/org/owasp/wrongsecrets/challenges/docker/Challenge28.java
> +        return SecretKey.equals(answer);
```suggestion
        return secretKey.equals(answer);
```

2023-03-10 22:22 UTC, commjoen commented on src/test/java/org/owasp/wrongsecrets/challenges/docker/Challenge28Test.java
> +        Assertions.assertThat(challenge.spoiler()).isEqualTo(new Spoiler(SecretKey));
```suggestion
        Assertions.assertThat(challenge.spoiler()).isEqualTo(new Spoiler(secretKey));
```

2023-03-10 22:22 UTC, commjoen commented on src/test/java/org/owasp/wrongsecrets/challenges/docker/Challenge28Test.java
> +        Assertions.assertThat(challenge.solved(SecretKey)).isTrue();
```suggestion
        Assertions.assertThat(challenge.solved(secretKey)).isTrue();
```

2023-03-11 12:06 UTC, puneeth072003 commented
@commjoen Issue as been created at #694 can you please send me your part of the message.

2023-03-11 22:50 UTC, commjoen approved these changes
Lgtm! Thank you @puneeth072003 !
@bendehaan would you be able to do one more round of textual reviewing on it please?

2023-03-13 15:12 UTC, bendehaan approved these changes

2023-03-13 15:14 UTC, merged