fix: save selected theme
OWASP/wrongsecrets pull request #715
Opened 2023-03-20 13:13 UTC by turjoc120

### What kind of changes does this PR include?

-   [x] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### Description

### Relations

### References

### Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] The PR passes pre-commit hooks and automated tests

2023-03-20 16:37 UTC, bendehaan commented on src/main/resources/static/theme-toggle.js
> -  const darkModeMediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
How about using this user preference as default initial setting, saving that to local storage?

2023-03-22 15:17 UTC, bendehaan requested changes
It looks like the user default prefrence now always overrides the user setting for the site?

2023-03-23 07:49 UTC, commjoen commented
Maybe it is better to capture this as a function with a jest test :-)?

2023-04-02 09:58 UTC, bendehaan commented
Hi @turjoc120, are you currently working on this fix, or planning to continue work anytime soon?

2023-04-07 04:39 UTC, commjoen commented on src/main/resources/static/theme-toggle.js
> +  const initialTheme = darkModeMediaQuery.matches || localStorage.getItem('darkMode') === 'true'
```suggestion
  const initialTheme = localStorage.getItem('darkMode') === 'true'
```
This fixed it for me :)

2023-04-08 12:46 UTC, bendehaan approved these changes

2023-04-08 13:36 UTC, merged