feat: add cli for scaffolding a new challenge
OWASP/wrongsecrets pull request #802
Opened 2023-05-02 17:42 UTC by nbaars

Refs: #555

2023-05-06 06:58 UTC, commjoen requested changes
Wow @nbaars this is a great start!
Thank you so much. I have some first feedback, can you please have a look at it ?

2023-05-06 06:58 UTC, commjoen commented on cli/Cargo.toml
> +[package]
Can you please add this path to the dependabot configuration :)

2023-05-06 06:58 UTC, commjoen commented on cli/README.md
> +First install [Rust](https://www.rust-lang.org/tools/install). Then open a terminal and type:
Maybe we can have a cross compiling and building github action with a download link to its attachments so people can copy it as well?

2023-05-06 06:58 UTC, commjoen commented on cli/README.md
> +- Add GitHub actions to build binary for the different platforms
ah yes :D this!

2023-05-06 06:58 UTC, commjoen commented on src/main/resources/challenge.hbs
> +@Order(0)
can we make the order also automatede in terms o the number?

2023-05-06 06:58 UTC, commjoen commented on src/main/resources/challenge.hbs
> +
```suggestion
/*
* <put your javadoc here describing the challenge in one sentence>
*/
```

2023-05-06 06:58 UTC, commjoen commented on src/main/resources/challenge.hbs
> +
```suggestion
     /**
     * {@inheritDoc}
     * uses {{technology}}.
     */
```

2023-05-06 06:58 UTC, commjoen commented on src/main/resources/challenge.hbs
> +        return "<<replace with correct answer>>";
```suggestion
        return "<<replace with correct answer but then obfuscated/encrypted in code>>";
```

2023-05-06 06:58 UTC, commjoen commented on cli/README.md
> +- Fix templating (not everything is present yet)
it would be nice to have some basic tests as well i guess :) ? Can you add those please?

2023-05-06 06:58 UTC, commjoen requested changes
Wow @nbaars this is a great start!
Thank you so much. I have some first feedback, can you please have a look at it ?

2023-09-29 04:22 UTC, commjoen commented
Elligible for `hacktoberfest-accepted` label if timely finished in october

2023-12-09 07:57 UTC, commjoen commented
Hi @nbaars ! Would you like to create a new iteration based on the refactor results please?

2024-01-01 22:40 UTC, commjoen commented
Hi @nbaars should we keep this one open to generate the required files :-)?

2024-01-17 08:28 UTC, nbaars commented
I'm going to rewrite this with [Spring Boot CLI](https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html). Much cleaner approach.

2024-01-17 08:28 UTC, closed without merging